flare_dir: ~/Projects/repos/magento-merchdocs/master-m2.3/
jekyll_dir: ~/Projects/repos/adobe/magento-docs/merchdocs/src/

#
# Learn more about XPath: https://www.w3schools.com/xml/xpath_syntax.asp
# Try your XPath: https://www.freeformatter.com/xpath-tester.html
#
# Learn more about CSS selectors: https://www.w3schools.com/CSSref/css_selectors.asp
# Try your CSS selector: https://try.jsoup.org/
#
# Note: Use node and attribute names without namespaces.
# For example, to specify "MadCap:Default.NewTag", use "Default.NewTag".
#
remove:
  #
  # XPath or CSS selectors of elements and all nested nodes to remove.
  #
  completely:
    - '[conditions="Default.NewTag"]'
    - '[conditions*=PrintOnly]'
    - '[conditions="Default.AppNum"]'
    - '[conditions="Default.AppNoNum"]'
    - '[conditions*="Not Needed"]'
    - '[conditions*="Not Ready"]'
    - '[conditions*=PDF]'
    - '[conditions="Default.Tooltips"]'
    - '[conditions="Default.Handout Only"]'
    - '[conditions="Default.UserGuide Only"]'
    - '[conditions="Default.Developer Mode Only"]'
    - '[conditions*=Deprecated]'
    - '[conditions="Default.2-2-4"]'
    - '[conditions="Default.2-2-5"]'
    - '[conditions="Default.2-3"]'
    - '[conditions="Default.Config Ref Only"]'
    - .Next
    - script
    - keyword
    - concept
    - p.clear
    - style
    - a[name]
    - glossaryProxy
  #
  # Attributes to remove.
  #
  attribute:
    - lastBlockDepth
    - lastWidth
    - lastHeight
    - autonum
    - style
    # toc attributes
    - BreakType
    - StartSection
    - PageNumberReset
    - PageLayout
    - PageNumberFormat
    - PageNumber
    - PageType
    - SectionNumberReset
    - VolumeNumberReset
    - ChapterNumberReset
    - ComputeToc
    - ReplaceMergeNode
    - AutoEndOnLeftPage
    - ChapterNumber

  
  #
  # Attributes to remove by name and value.
  # Name is at the left, value is at the right.
  # For example, to remove attributes conditions="Default.Verify" and conditions="Default.Not in B2B"
  #
  # conditions:
  #   - Default.Verify
  #   - Default.Not in B2B
  #
  attribute_with_value:
    conditions:
      - Default.Verify
      - Default.Not in B2B
      - Default.ScreenOnly
    class:
      - tableBody
      - Contrast
      - Command
      - ToDo
      - largeDiagramNoPopup
      - _30pct
      - _30pctNoBorder
      - Black
      - NoBullet
      - TableDDFlushLeft
      - TableCell

  #
  # XPath or CSS selectors of elements to remove.
  # All nested elements will be kept the same.
  #
  element_itself:
    - dropDown
    - dropDownHead
    - dropDownBody
    - div.Image
    - div.pageTitleContainer
    - div.FloatLeft_th
    - div.FloatRight_desc
    # - '[class^=TableStyle-]'
    - div
    - glossaryTerm
    - '[class^=IndentAfter]'
    - conditionalText:not([conditions])
    - b.Contrast
    - .NoBullet
    - '[class*=TableStyle-Code]'

    # - TableStyle-Guidelines
    # - [TableStyle-Definitions] # attributes that contain TableStyle-Definitions in class name
    # - '[^TableStyle-Code]' # attributes that contain TableStyle-Code in class name


#
# XPath or CSS selectors of elements to swap.
# A new element is at the left and old elements are at the right.
# An example of how to rename both elements <dropDownHotspot/> and <p class="ToDo"/> to <h2/>, while keeping content the same.
# h2:
#   - dropDownHotspot
#   - p.ToDo
#
swap:
  element_names:
    h1:
      - body > h2:first-child
      - body > h3:first-child
      - body > h4:first-child
      - body > h5:first-child
      - body > h6:first-child

    h2:
      - p.ToDo
      - p.ItemHead
      - dropDownHotspot

    # h3:
    #   - caption

    li:
      - '[class^=Number]'
      - '[class^=Alpha]'
    
    # ol:
    #   - '//*[@class="Number1"]/parent::dropDownBody'
    #   - '//*[@class="Number1SubSeries"]/parent::dropDownBody'
    
    a:
      - xref
      - b[href]
    
    include:
      - snippetBlock
      - snippetText
    
    b:
      - caption

    p:
      - //tbody[not(ancestor::table)]

    # code:
    #   - pre
  
  # <New value> : <XPath of the attribute value to replace>
  # attribute_values:
  #   'bs-callout bs-callout-info': '//div[@class="note"]/@class'



  
add:
  parent:
    p:
    - p[class^=note]
    - //img/following-sibling::text()
    ul:
    - li[class*=Alpha]
    
  
