  #
  # Learn more about XPath: https://www.w3schools.com/xml/xpath_syntax.asp
  # Try your XPath: https://www.freeformatter.com/xpath-tester.html
  #
  # Learn more about CSS selectors: https://www.w3schools.com/CSSref/css_selectors.asp
  # Try your CSS selector: https://try.jsoup.org/
  #
  # Note: Use node and attribute names without namespaces.
  # For example, to specify "MadCap:Default.NewTag", use "Default.NewTag".
  #
remove:
  #
  # XPath or CSS selectors of elements and all nested nodes to remove.
  #
  completely:
    - '[conditions="Default.NewTag"]'
    - '[conditions="Default.PrintOnly"]'
    - '[conditions="Default.AppNum"]'
    - '[conditions="Default.AppNoNum"]'
    - '[conditions="Default.Not Needed"]'
    - '[conditions="Default.Not Ready for Publish"]'
    - '[conditions="Default.Tooltips"]'
    - '[conditions="Default.Handout Only"]'
    - '[conditions="Default.UserGuide Only"]'
    - '[conditions="Default.Developer Mode Only"]'
    - '[conditions="Default.Deprecated"]'
    - '[conditions="Default.2-2-4"]'
    - '[conditions="Default.2-2-5"]'
    - '[conditions="Default.2-3"]'
    - '[conditions="Default.Config Ref Only"]'
    - '[conditions="Default.Not in B2B PDF"]'
    - '[conditions="Default.Not in EE"]'
    - '[conditions="Default.EE Screenshot,Default.Not in B2B"]'
    - div.Next
    - script
    - col
    - keyword
    - concept
    - p.clear
  
  #
  # Attributes to remove.
  #
  attribute:
    - lastBlockDepth
    - lastWidth
    - lastHeight
    - autonum
  
  #
  # Attributes to remove by name and value.
  # Name is at the left, value is at the right.
  # For example, to remove attributes conditions="Default.Verify" and conditions="Default.Not in B2B"
  #
  # conditions:
  #   - Default.Verify
  #   - Default.Not in B2B
  #
  attribute_with_value:
    conditions:
      - Default.Verify
      - Default.Not in B2B
      - Default.ScreenOnly
    class:
      - tableBody

  #
  # XPath or CSS selectors of elements to remove.
  # All nested elements will be kept the same.
  #
  element_itself:
    - dropDown
    - dropDownHead
    - div.Image
    - div.pageTitleContainer
    - dropDownBody
    - div.FloatLeft_th
    - div.FloatRight_desc
    # - TableStyle-Guidelines
    # - [TableStyle-Definitions] # attributes that contain TableStyle-Definitions in class name
    # - '[^TableStyle-Code]' # attributes that contain TableStyle-Code in class name


#
# XPath or CSS selectors of elements to swap.
# A new element is at the left and old elements are at the right.
# An example of how to rename both elements <dropDownHotspot/> and <p class="ToDo"/> to <h2/>, while keeping content the same.
# h2:
#   - dropDownHotspot
#   - p.ToDo
#
swap:
  h2:
    - dropDownHotspot
    - p.ToDo
    - p.ItemHead
  h3:
    - caption
    - p.TableHeadingOrange
    - p.TableHeading
  ol:
    - p.Number1
    - p.Alpha1
  li:
    - p.NumberContinue
    - p.AlphaContinue
  div:
    - p.note

  